(setq assert-is (fn (expectation value)
    (assert (is expectation value))))

(setq assert-nil (fn (value)
    (assert-is nil value)))

(setq assert-not-nil (fn (value)
    (assert value)))

(setq equals (fn (a b)
  (if (and (atom a) (atom b))
    (is a b)
    (do
      (while (and (not (atom a)) (not (atom b))
                  (equals (car a) (car b)))
        (setq a (cdr a))
        (setq b (cdr b)))
      (and (atom a) (atom b) (is a b))))))

(setq assert-equals (fn (expectation value)
    (assert (equals expectation value))))

(setq assert-not-equals (fn (expectation value)
    (assert (not (equals expectation value)))))

(assert-equals 1 1)
(assert-equals 'hello 'hello)
(assert-equals '("hello" "world") '("hello" "world"))
(assert-equals '('("wow") 1) '('("wow") 1))
(assert-not-equals '('("wow") 1) '('("wow") 2))
(assert-not-equals '('("bow") 1) '('("wow") 1))
